### ISSUE TITLE
ユースケースを確定する

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-api#12]
最新のユースケースシナリオはこちら
https://miro.com/app/board/o9J_laUr9s8=/
閲覧パスワードは `remote-monitoring` です。何か補足や懸念等あればコメントを入れて下さい。

元になった、takahashimさん作成の[ユースケース](https://docs.google.com/presentation/d/1VncKMMdmNZ_XxkSD0nAVO363FNSS6oh_S8TtijnzNDw/edit#slide=id.p)

**Comment by halsk** [comment]
これとは別に、ハイリスク患者向けには、自動でデータが取れるパルスオキシメーターと、Android端末をセットにして送り、データ測定を自動化するというユースケースも存在する。

**Comment by diizuka2** [comment]
ユースケース図だけでは不足です。
ユースケースシナリオを書き下した方が、システムと人、人と人との関係、情報をいつどんな順序で誰から誰に渡す、が明らかになります。
参考：ユースケース実践ガイド https://www.amazon.co.jp/dp/4798101273

試しに書いてみます。過不足間違いの指摘は歓迎です。
これをもとに、いや違うこうあるべき、という議論を繰り貸して、システムとしてあるべき姿を明らかにした上で、実装すべき機能に落とし込み、実装していきます。

## ユースケースシナリオ
自宅療養者を遠隔患者モニタリングシステムに初期登録する

### 登場人物
- 自宅療養者
- 保健師
- 遠隔患者モニタリングシステム

### 事前条件
- 自宅療養者は、保健所に届け出てPCR検査をうけ、コロナ陽性と判明している
- 自宅療養者は、遠隔患者モニタリングシステムを使い、自宅療養を希望している
- 自宅療養者は、スマートフォーンを所持し、インターネットにアクセスできる
- 遠隔患者モニタリングシステムは、自宅療養者が持つスマーフォンの電話番号を知っている

### 事後条件
- 自宅療養者が、遠隔患者モニタリングシステムを使えるようになっている

### 基本フロー
1. 保健師は、遠隔患者モニタリングシステムの使用法を記した書簡を、郵送等で自宅療養者に送付する。
　-  電子メールやSMS、LINE経由で、上記書簡の内容を参照できるURLを送付しても良い

1. 自宅療養者は、スマートフォンのWebブラウザを使い、受け取った書簡に記された
遠隔患者モニタリングシステムへのアクセス用URLを開く。
　- QRコードで書かれていると良い。
　-  自宅療養者毎に独自のURLになっていて、初回のuser/pass入力を省略できると良い

1. 遠隔患者モニタリングシステムは、本人確認のため自宅療養者の電話番号宛にSMSを送付する
   - これをやらないと、URLに総当たり攻撃を受ける事で、なりすましが出来てしまう
1. 自宅療養者は、SMS中にあるURLを開く。必要に応じてuser/passを入力する
1. 遠隔患者モニタリングシステムは、アクセスして来たのが本人であるとみなし、cookieを発行する。
1. 自宅療養者は 以降、user/pass不要で遠隔患者モニタリングシステムにアクセスできる

### 代替フロー
1. 自宅療養者がしばらくの間(1週間?)、遠隔患者モニタリングシステムアクセスしないと、cokkieの有効期限が切れる。スマートフォンを買い替えたりすると、cokkieの有効期限が切れる。. 
    -  自宅療養者が久しぶりに遠隔患者モニタリングシステムにアクセスする
    - 遠隔患者モニタリングシステムは、SMSを送付する。以降は基本フローと同様

**Comment by takahashim** [comment]
コメントありがとうございます。確かにユースケース図は（良くも悪くも）ざっくりしてるんですよね。

ユースケース図の目的や、ユースケース記述の粒度にはいろいろあるかと思いますが、まずユースケース図を起こしてみたのは、

* アクターの明確化（たとえば本システムは患者さんと保健師さん以外触らせないでよいかどうか、それとも道庁の方やその他の方が出てくるか）
* システム境界の明確化（困ったときには主に電話連絡にフォールバックするのではないかと推測しているのですが、それを踏まえてシステム側が持つ機能をどこまで想定するか）

に役立つかなあと思って作ってみたのでした。

**Comment by y2naranja** [comment]
>  電子メールやSMS、LINE経由で、上記書簡の内容を参照できるURLを送付しても良い

保健師さんと待機者の双方に一定のITリテラシーが必要になる場合、オペ教だけで保健師さんにかなりの負担がかかります。
今は保健師さんを臨時に募って対応しているとのことなので、機械が苦手な方が一定数いると考えた方が良いと思います。

待機者の想定を60-70代くらいに置いて、なるべく手段は絞り込み（できれば一本化。でないと、保健師さんが出したりチェックしたりするものの種類や入出力が多過ぎて作業が倍増する）、かつ、操作・説明し易いものが良いかと思います。

LINEのトークメニューにマニュアルを仕込む手も考えましたが、恐らく多くの方が、そのためにLINEアカウントを開設することを考えると、あまり現実的ではないかもと思いました。

なお参考までに、自分の孤独死防止のために登録しているLINEサービスをご紹介しておきます。1日1回安否確認が来て、一定日数返答がないと本人に電話が来て、応答がなければ設定した緊急連絡先に連絡が行きます。

https://www.enrich.tokyo/index.html
![Screenshot_20201228-133753-picsay.jpg](https://user-images.githubusercontent.com/912713/103191690-44126b80-4919-11eb-9903-b187c0608929.jpg)
![Screenshot_20201228-133929-picsay (1).jpg](https://user-images.githubusercontent.com/912713/103191764-8176f900-4919-11eb-9c7d-11df6d201f27.jpg)

**Comment by halsk** [comment]
みなさん、ありがとうございます。
@takahashim さん、@diizuka2 さん、いただいた情報から、こちらのユースケースシナリオを作りました。
https://miro.com/app/board/o9J_laUr9s8=/
閲覧パスワードは `remote-monitoring` です。何か補足や懸念等あればコメントを入れていただければと思います。

**Comment by halsk** [comment]
シナリオは作ったのでクローズします。
