### ISSUE TITLE
認証方法をどうするか

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/remote-patient-monitoring-api#13]
患者（モバイル）側、保健師側の両方で認証が必要そうです。

## 患者側

* ふつうにID/Password方式でよいのか
    * 使いこなせるかどうかが割と心配…（紙に書いたIDとパスワードを渡す方式ならいける？）
* IDはメールアドレスにするか、それとも何らかのIDにするか
    * なんとなく、保健所側で発行する方が確実な気もする。おそらく現状の保健所ではメールアドレスは管理してなさそうだし。
    * ちなみに保健所からメールを飛ばせる必要はある？
* パスワードは再発行できるようにするか
    * 忘れたら電話してもらって、電話口で教えた方が早そうな気もする（特にメールアドレスを管理しない場合。まあSMSを使う方法もありますが）。基本的には2週間程度有効であればよいはずだし

## 保健師側

* 複数人が見る場合、厳密に（保健師ごとに）ID・パスワード管理を行うべき？
    * その場合、保健所側の作業になるのか、システム管理者？側の作業になるのか
    * 個人情報保護規程みたいなものでauditのルールが決まっていたりする？（認証とはちょっとずれますが、いつ誰がどのデータを見たかが全てtrackingできないとNGなのか、ふつうにダッシュボード的に表示してるんだからログインした人＝見てる人という前提が成り立たないので気にしなくてOKなのかが気になってます）

**Comment by takahashim** [comment]
認証の強度というかデリケートさは、個人情報（含むメールアドレス、電話番号）をシステム内に入れるかどうかにもよると思っていて、強い気持ちで個人情報を登録しない・させない形で運用できれば、比較的ゆるい形でもいけるのではないかという気持ちがあります（ただし、途中でやっぱり個人情報を入れたいよね…という話になると仕様の大変更が必要になるかもしれません）。

**Comment by halsk** [comment]
ありがとうございます。
個人情報を扱うと一気に調整コストが上がるので、以下を想定しています。

* 匿名ID/パスワードを保健所から発行
* 紙/メールで渡す（保健所からメールで送る場合、ID発行と同時にメールアドレスを入れてメールすれば良いかも。運用が可能かどうか確認）
* パスワード編集/再発行はできた方が良いかもですね。

保健師側は奥村先生に確認しましょう。

**Comment by diizuka2** [comment]
Mustではないですが、初回ログイン時であっても、userid/pwを入力する手間を無くせないかと思っています。
携帯からある番号に電話すると、発信者電話番号から患者を特定し、患者専用でPW入力不要なログイン用URLをSMSで発行、とかです。

くわえて、useridやpwを全角文字での入力も許した方が良いかと思います。
私の母は後期高齢者で、携帯の日本語入力モードの切り替えや、全角半角の違いを理解していません。
数字やアルファベットを入力するときは、「いち」とかを日本語入力して変換して入力するので、全角になります。

**Comment by halsk** [comment]
ありがとうございます。SMS自体が使えるかどうかがまだ確定しておらず、いずれにせよ一般的な認証機構を作り、それを拡張することになると思いますので、一般的な User/Password で実装は考えます。
（あとからSMSでの認証などを追加することは可能ですのえ。）

技術的には、、AWS Cognito での認証実装を考えています。

**Comment by Lunefh** [comment]
みなさまおつかれさまですm(_ _)m

ものすごく今さらな疑問なのですが、モニタリングキットの患者さんへのお渡しは、郵送等が想定されていますでしょうか？(早めに気づけなくてすみません🙇‍♂️)

誰かが保健所かITステーションから直接届けに行けるのであれば、感染予防の対策は要りますが、アプリのインストールや装着・操作方法の代行や説明などを、お渡し時に出来るのではないかと…。

とはいえ人手と感染リスクを考えると、郵送一択としておいた方がベターという感じでしょうか…？(そうなると、配達の方の感染リスクも充分に考慮せねばなりませぬが)

技術の方は全く分からず誠に申し訳ないのですが、運用・保守の段階になると、病床での電池交換や運用サポートに、色々と人的なフォローが必要になりそうな気がしました…。(医療者必須の部分と分割することができれば、かなり運用は楽になるかもとは思います)

**Comment by halsk** [comment]
Cognito で、レコードごとの認証までは必要ないという方向で決めます。
