### ISSUE TITLE
AGPLv3 ライセンスへ変更する (was: MPL ライセンスへの変更について)

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-api#141]
関わっていただいた皆様で、反対意見があればぜひお伺いしたいと思うのですが、今MITとなっている本システムのライセンスを、MPL ライセンスに変更したいと考えています。
以下のような理由です。

* 「症状の報告」に特化したシステムとなっており、再利用する先も症状報告が多いと予想する
* 上記のようなことからも、 本システムの利用ユーザは企業が多いと思われる
* コミュニティへの参加者は限られてしまいフィードバック量も少ないだろう
* センシティブな情報を扱うことやシステムへの継続的な信頼性があることから、営利企業が自治体等から委託される形で使われることが多いだろう
* MITライセンスだと、再利用された先のソースコードが公開されず、改善がフィードバックされなくなってしまう

賛成、反対などぜひご意見ください。

**Comment by takahashim** [comment]
議論の参考として、MPL(Mozilla Public License)についての情報も載せておきます：

* MPL 2.0原文 https://www.mozilla.org/en-US/MPL/2.0/
    * Open Source Group Japanによる参考訳 https://licenses.opensource.jp/MPL-2.0/MPL-2.0.html
    * Mozillaパブリック・ライセンス(MPL) バージョン2.0 日本語参考訳 https://note.com/note_s/n/n4a0f37ea8920
* MPL 2.0 FAQ https://www.mozilla.org/en-US/MPL/2.0/FAQ/

**Comment by takahashim** [comment]
> MITライセンスだと、再利用された先のソースコードが公開されず、改善がフィードバックされなくなってしまう

MPLでも、Webアプリケーションとして使う場合にはdistributeしたことにならないため、ソースコードの開示義務は制限されそうです（MPL 2.0 FAQ「Q17: What does "distribute" mean?」参照）。

例えばサービスの開発と運用を同じ企業で行う場合、ソースコード自体は自治体に納品しないで自分が契約するクラウドを介してサービスを提供するだけという形であれば、自治体・保健所・エンドユーザーの誰にもsoftwareをdistributeしていないことになるため、フロントエンドのHTML・CSS・JavaScript以外のソースを開示する義務がなくなります（スマホアプリ等を提供するようになった場合、アプリ部分についてはdistributeすることになるため、スマホアプリのソースコード開示義務は発生します）。

どこまでフィードバックを求めるかにもよりますが、切実にフィードバックを期待するのであれば、AGPLv3等も検討した方が良いかと思います。 https://ja.wikipedia.org/wiki/GNU_Affero_General_Public_License

**Comment by halsk** [comment]
@takahashim さん
なるほど。そういう意味であれば、AGPLv3 のほうが良さそうですね。
