### ISSUE TITLE
DEVELOPMENT.mdの改善提案

### ISSUE THREAD

**Issue by garasubo** [codeforjapan/remote-patient-monitoring-api#145]
実際にこのレポジトリをデプロイして詰まった部分についていくつか補足の説明を足したいです。

具体的には

- `aws configure`に関する説明
- `config/dev.json`の不要な行の削除

**Comment by tkgshn** [comment]
確かに @garasubo さんが[書いてくれた記事](https://zenn.dev/garasubo/articles/4336405b222c7b9de1b2)を見てると、このREADMEとセットアップまでの間に結構難しいポイントがありそうですね。自分がこれHerokuのワンクリックデプロイなどのボタンを作成しましょうか！？ cc @halsk

**Comment by NEKOYASAN** [comment]
Serverless Frameworkだと思いますがHerokuでデプロイ可能なのでしょうか...？
garasuboさんの説明追加で十分だと思いますがどうでしょうか

**Comment by tkgshn** [comment]
理想系としては、GithubやAWSを開かなくても問題ないようにする...という感じですね
https://twitter.com/ask_yoshi_taka/status/1389551639346892804?s=20

**Comment by NEKOYASAN** [comment]
運用や保守の段階で少なくともAWSを触る必要はでてくると思っています。
またProductionで提供する際には保健所などの公共機関に対する提供で、かつ人の生死にも関わるとてもセンシティブなものであるとも思っています。
SaaSのような形でどこかの会社が責任を持って運用・保守を行うという形であれば問題ありませんが、一般の方・AWSの知識などがない方がデプロイをするというのは危険でほぼないことだと思います。
なので開発者が開発用に環境を作ることがメインになるかと思いますので開発者向けに開発環境を作りやすくするのはコントリビュートしやすくすることにもつながるためとてもよいと思いますのでドキュメントを整備するという方向の方が良いと思います。
