### ISSUE TITLE
API の定義をする

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-api#15]

**Comment by halsk** [comment]
一旦 API 定義をしました。github pages で見れるようにしています。
（GitHub Pagesからは実際のAPIは叩けません。）
どなたかレビューいただけると嬉しいです！

https://codeforjapan.github.io/remote-patient-monitoring-api/

#6  とも関連

**Comment by kaizumaki** [comment]
フロント側を作っていた観点からすると、このAPI定義で十分のような気がします。
ちなみに、 `/api/center/{centerId}/patient/` をダッシュボードの患者一覧につなぎこむのだと思いますが、グラフの時系列データは `statuses` の配列からとるのですよね。これって基本的に計測始めてからすべてのデータが入るのでしょうか？どれくらいグラフのX軸がのびるのかが気になっています。

**Comment by halsk** [comment]
ありがとうございます。とりあえず、一患者あたり10件くらいを返そうかと思っています。5日分だと少ないかな。
SpO2の自動送信データが入ってくる場合は間引かないとだめだと思いますが

**Comment by takahashim** [comment]
API定義ありがとうございます。見てみました。

* 例えば患者の監視終了する処理は`PUT /api/patient/{patientId}`を使っても実現できそうですが、専用のAPIを用意しなくても問題なさそうでしょうか？
* 例えば`GET /api/patient/{patientId}`は患者側でも保健師側でも使いそうですが、特に区別する必要はなさそうでしょうか？
* `observer`は他の文脈（observerパターン等）でよく使うタームなので、他に良い名前があったら変えた方がいいかも…？　という気がしました（とはいえパス名だし問題ないかも？）

Cognitoをよく分かってない（使ったことない）ので外してるかもしれませんが、APIを叩く側のroleによって挙動を変えたそうなところをどういう風に実現するのかな？と思いました。患者と保健師で見せたいデータが違う（保健師には見せたいけど患者には見せたくない）とか、患者には叩かせたくないといった違いがありそうなので。

**Comment by halsk** [comment]
@takahashim ありがとうございます。

> 例えば患者の監視終了する処理はPUT /api/patient/{patientId}を使っても実現できそうですが、専用のAPIを用意しなくても問題なさそうでしょうか？

別に作っても良いかもしれませんね。
`GET /api/patient/{patientId}` は、患者の場合は自分のデータしか見れず、保健師の場合は自分が所属する保健所に登録されているデータしか見れません。この場合、別にAPIを分けた方が良いですかね？

observer、確かにそうですね。nurse の方が良いかな？

APIを叩く側のroleによって挙動を変えるには、lambda 関数を Authorizer にしてその中でロジックで分ける形になりそうですが、そのような面倒なことをするなら、最初からエントリポイント自体を分けた方がシンプルになりそうだなと思い至りました。

```
/api/admins/patient/{patientId}
/api/nurses/patient/{patientId}
/api/users/paitnet/{patientId}
```

みたいにしたほうが良いですかね？

**Comment by takahashim** [comment]
> GET /api/patient/{patientId} は、患者の場合は自分のデータしか見れず、保健師の場合は自分が所属する保健所に登録されているデータしか見れません。この場合、別にAPIを分けた方が良いですかね？

同じままでもよいですが、role等によってGETでは何が返ってくるのか、PUTでは何が更新できるのか、「取得はできるけど更新はできない」みたいなものがあるのかないのか…みたいな情報を、適切にフロント側とサーバ側で共有するのに工夫が必要そう、というのが懸念でした。

> そのような面倒なことをするなら、最初からエントリポイント自体を分けた方がシンプルになりそうだなと思い至りました。

ああ、たしかにそれがシンプルですね :+1:　上記の懸念も解決しそうです（エントリポイントで区別すれば良くなる）。
サーバ側は実装する要素が増えるかもしれませんが複雑さは減りますし、フロント側は必要なAPIだけ見れば良くなるので単純にシンプルになりそうです。

**Comment by halsk** [comment]
ではその方向で書き直します！

**Comment by halsk** [comment]
@takahashim 
定義を作り直しました。
https://codeforjapan.github.io/remote-patient-monitoring-api/
`/api/admin/`, `/api/nurse/`, `/api/patient/` の3つにパスを分割しています。
これに合わせ、UserPool も Admin/Nurse/Patient の3つをつくり、それ毎に Authorization をするように変更します。

**Comment by takahashim** [comment]
おー、どのroleからどれが使えるかはすごく分かりやすくなりました！
例えばCenterについてだと、保健師は参照しかできないし、療養者は一切見られない（知らなくてOK）、ということですよね。

**Comment by takahashim** [comment]
細かいAPIの不足について：

* Statusは削除のフロー（miroのU04）があるので（たぶん間違って入力したデータを取り消すものですよね）、patientからDELETEが必要なはずです。

* 過去の症状の一覧が必要ですが（U03）、これは`GET ​/api​/patient​/patient​/{patientId}` で合わせて取得するイメージでしょうか。

* U20で療養者のニックネームを変更できるようですが、これはPatientの属性に含まれることになる（ただし療養者のAPIからは見られない）のでしょうか。

* 各roleのログイン・ログアウトのAPIもここに追加することになりますか？

**Comment by halsk** [comment]
@takahashim 
コメントありがとうございます。

> Statusは削除のフロー（miroのU04）があるので（たぶん間違って入力したデータを取り消すものですよね）、patientからDELETEが必要なはずです。

削除はこちらにあります。
https://codeforjapan.github.io/remote-patient-monitoring-api/#/Status/delete_api_patient_status__statusId_

> 過去の症状の一覧が必要ですが（U03）、これはGET ​/api​/patient​/patient​/{patientId} で合わせて取得するイメージでしょうか。

一覧は、GET ​/api​/patient​/patient​/{patientId}​/statuses ですね。 /patient/{patientId} にも症状が含まれていますが、最新の10件だけ取ってきます。

> U20で療養者のニックネームを変更できるようですが、これはPatientの属性に含まれることになる（ただし療養者のAPIからは見られない）のでしょうか。

ニックネームはメモになりますね。そういえばこの部分はまだ確定していません。サーバで扱わずに、ローカルのみのメモとして使う（localstrage で実装？）という案が出ています。

> 各roleのログイン・ログアウトのAPIもここに追加することになりますか？

はい。そうですね。今から作ります。

**Comment by kaizumaki** [comment]
@halsk フロント側の実装を進めており、typoじゃないかと思われる箇所を発見しましたのでお知らせしておきますね。
`symptom` の
`couth` -> `cough`
`phiegm` -> `phlegm`
