### ISSUE TITLE
利用規約を作る

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-api#2]
大阪の例

http://www.pref.osaka.lg.jp/iryo/2019ncov/sisutemuriyoukiyaku.html

**Comment by kasushiro** [comment]
高薄（たかすすき）です。
大阪府のWordファイルより少し修正してみました。
・システム名：（仮）COVID-19自宅・宿泊施設患者遠隔モニタシステム
・大阪府→北海道
・データ収集範囲に項目追加
[riyoukiyaku.docx](https://github.com/codeforjapan/remote-patient-monitoring/files/5743386/riyoukiyaku.docx)

まずはたたき台として、いかがでしょうか。

**Comment by halsk** [comment]
ありがとうございます！大変助かります。

**Comment by kasushiro** [comment]
道でイベントや施設利用時にメールアドレスを登録して、感染が発生した際にお知らせするシステムがあります。
この利用規約を参考にお知らせします。

北海道コロナ通知システム
http://www.pref.hokkaido.lg.jp/kz/kks/coronaalertsystem.htm

利用規約
http://www.pref.hokkaido.lg.jp/kz/kks/coronaalertsystem-kaitei.htm

よろしくお願いします。

**Comment by kasushiro** [comment]
@halsk お疲れ様です。本日のUI/UXの打ち合わせに出られず、すみません。個人情報の取り扱いで、参考までに、上記の道が運営するコロナ通知システムはメールアドレスを登録させる仕組みなので、今回の取り扱いと同様かと思いました。規約には、氏名や住所、電話番号は保持しないとの記載になってます。ご参考までに。よろしくお願いします。

**Comment by halsk** [comment]
ありがとうございます！メールアドレスはokだが、電話番号はNG、ということなんですかね。

**Comment by kasushiro** [comment]
コロナ通知システムでは、メールアドレスのみですね。こんかいは電話番号も登録させるのですか？
電話番号とメールアドレスの組み合わせで、個人情報の扱いなるか、なった場合、どうなるか、もう少し調べてみますね。

**Comment by halsk** [comment]
SMSが送れれば、メールアドレスは必要ないです。用途としては、ID/パスワードの通知や、データが更新されていない時のリマインドのために使います。
メールアドレスだと気づかないことも多いと思いますので、SMSの方が望ましいのです。

**Comment by y2naranja** [comment]
それだと、SMS通知を有効にしてもらう必要がありますね。
私は以前、特殊詐欺やスパム除けにずっと無効にしていたことがあるので、無効にしている方向けに、その辺の文言が必要かもです。

**Comment by kasushiro** [comment]
ありがとうございます。

個人情報保護について、メールアドレス単体では個人情報にあたらないようですが、
個人名になっていた場合は特定できることから、取り扱いには注意が必要とのコメントでした。
https://www.soumu.go.jp/main_sosiki/gyoukan/kanri/question03.html
携帯電話番号が対象かどうかは調べられませんでした。
どちらにしても、規約に利用目的、範囲の記載は必要かと思います。

SMSかメールアドレスかについて、総務省の受信数の調べでは、
ほぼ同率でした、
「スマートフォンの一日平均利用、キャリアメールは3.2回、SMSは4.0回、LINEは10.2回送信
キャリアメールは「0回」が最多で59.0％、次いで「1～10回」が35.5％となった。
SMSもキャリアメール同様「0回」が最多で56.5％、次いで「1～10回」が35.6％となった。」
https://mmdlabo.jp/investigation/detail_1844.html


「SMSは送信制限の甲斐もあり迷惑メッセージが少ないため、受信相手の目に留まりやすいのです。
その注目度を生かし、法人は集客や本人確認のために、個人は確実に相手へと伝えるために、SMSを活用することが多い」
https://www.karaden.jp/column/sms-not-delivered.html

届かない理由は@y2naranjaさんがおっしゃっていた通り、拒否されている場合と、
WiFi環境では受信できない点でしょうか。
あと、少ないかもしれませんが、SMSの契約をしていない場合もあるようです。

個人的には、キャリアメールは各社の迷惑メール対策や持っていないかとも多いことを想定して
SMSの方が良いかと思います。
y2naranjaさんの通り、SMSで届かない場合のガイドが必要ですね。

よろしくお願いします。

**Comment by kasushiro** [comment]
しばらく時間が空いてしまい、申し訳ありません。
利用規約を一部修正しました。
・ユーザ名　→　ログインID（ヘルプ画面のイメージより）
・第3条（１）利用開始　修正（携帯電話番号のショートメールの記載追加）
「利用者は、北海道が発行したログインID及びパスワードを利用者の携帯電話番号のショートメールサービス（以下、SMS）で受け取った時点で、システムの利用が開始できます。」

1/12の打ち合わせで、弁護士様にご確認とのことでしたので、修正等がある場合はご連絡ください。
システム利用の際に確認するかと思いますが、テキストの方が組み込みやすいようであれば、おっしゃってください。

よろしくお願いします。

[riyoukiyaku_Ver0.8.docx](https://github.com/codeforjapan/remote-patient-monitoring-api/files/5867857/riyoukiyaku_Ver0.8.docx)

**Comment by kaizumaki** [comment]
そろそろ利用規約をアプリに実装したいと思います。
道庁への確認は必要ないでしょうか...？

**Comment by kasushiro** [comment]
@kaizumaki ありがとうございます。
道庁への確認、必要だと思いますね。道から発信の場合のチェックもあると思います。
@halsk 先生経由で確認をお願いするイメージでしょうか。

Wordの文書ですが、同じ内容でテキストにもしました。
[riyoukiyaku.txt](https://github.com/codeforjapan/remote-patient-monitoring-api/files/6094849/riyoukiyaku.txt)

ご活用ください。

よろしくお願いします。

**Comment by y2naranja** [comment]
利用規約のログインID/パスワードについてですが、内部的には存在しますが、療養者はログイン時に入力しない（自分のログインID/パスワードは知らない）方向になっていたかと思うので、療養者に見せる利用規約には記載しない方が良いのではないでしょうか。

**Comment by halsk** [comment]
こちら、CfJ の顧問弁護士の方でレビューした利用規約です。
[【CFJ】riyoukiyaku_Ver0.9.onoda2021.3.10（再修正版）.docx](https://github.com/codeforjapan/remote-patient-monitoring-api/files/6119743/CFJ.riyoukiyaku_Ver0.9.onoda2021.3.10.docx)

**Comment by kasushiro** [comment]
テキスト版をUpします。
[遠隔療養者モニタリングシステム利用規約.txt](https://github.com/codeforjapan/remote-patient-monitoring-api/files/6150427/default.txt)

**Comment by halsk** [comment]
皆様ご協力ありがとうございました。反映させました！
