### ISSUE TITLE
APIの実装をする

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-api#31]
Issueとして立てました。

## 前回から進んだこと。
- jest を使って、e2e テストを先に書くことにした。（まだ途中）
- テスト用に、db の初期化や authentication 系のコードを追加した
- sls offline で、lambda をローカル実行できるようにした(DEVELOPMENT.md を参照のこと)

## e2e テストシナリオ

実装しようとしているテストシナリオは下記。ユニットテストはとりあえず後回し。`--runInBand` で逐次実行する。
テストケースが一通り書ければ、作業分担がしやすくなる。
リファクタリングもやりやすい。

- truncate tables
- anonymous で API を叩く。 `/get/centers` 等の一部のコマンド以外はエラーになることを確認
- admin user でログインできることを確認
- admin user の IdToken を `Authorization` ヘッダにセットして、下記を実行
  - center への get/post/put 操作
  - patient への get/post/put 操作
  - nurse の登録操作（Cognito でユーザを作る）
  - status の get/put 操作
- 前段階のテストで作成した nurse アカウントでログインできることを確認
- nurse user の IdToken を `Authorization` ヘッダにセットして、下記を実行
  - admin 系の操作ができないこと
  - patient の get/post/put 操作
  - status の get/put 操作
- 前段階のテストで作成した patient アカウントでログインできることを確認
- patient user の IdToken を `Authorization` ヘッダにセットして、下記を実行
  - admin/nurse 系の操作ができないこと
  - status の get/post/delete 操作
- truncate tables

## 残作業(プライオリティ高い順)

- [x] テストシナリオの残りを書く（とりあえず期待する動作のみで中身は書かない）
- [x] ユーザ登録まわりの処理を書く(そうしないと nurse とかのコードが書けない)
- [x] 残りの処理を書く(現在は /admin/ の一部しか無い)
- [ ] リファクタリング
- [x] ユニットテストを書く

## 何かおかしいところ

デプロイ後、lambda が実行できなくなるときがある。[こちらの手順](https://km-tech.hateblo.jp/entry/2019/12/06/181743) で直る。

## 誰かに見て欲しいところ

serverless.yml の書き方が美しくない気がする。
~~特に、API Gateway の CLIENT_POOL を設定するために2回デプロイしているところ。更に、手動で deploy api しないとその情報が反映されないので不便。~~ #50 で解決。

**Comment by ghost** [comment]
@halsk さん
お忙しいところ大変恐縮です。(PRのマージありがとうございました。)
お時間があるときで構いませんので本Issueについて1点、ご確認をさせてください。

> 残作業(プライオリティ高い順)

に挙げていただいている項目で今、何かお手伝いできることはありますでしょうか?
私自身、TypeScriptを用いたLambda実装の経験はありますので何かあればと
考えています。

もしAPI実装であればPRの単位・含めるものなどを提示いただけると幸いです。

特にアサインできるものは今のところないということでしたら大丈夫です。
よろしくお願いいたします。

**Comment by halsk** [comment]
@kE-sakai さん、ありがとうございます！！！

先程、一通りのテストを skip 状態にしてpush しました。今 skip にしている部分を実装していっていただけると大変助かります。
特に、以下の Status 系です。
![image](https://user-images.githubusercontent.com/16509/106386582-05d90200-6419-11eb-80e4-208a5d71e7c8.png)
これができると、クライアント側で接続が開始できます。

それぞれ、実装単位で Issue を作ってもらえると嬉しいです。（lambda 一つに 1 Issueくらいだとちょうど良いかも）

仕様については、[Swagger UI](https://codeforjapan.github.io/remote-patient-monitoring-api/) をご確認いただけると良いかと思います。

不明点も多いと思うので、随時聞いて頂けると助かります！

**Comment by halsk** [comment]
なお、かぶってしまうと困るので、実装を始めるときには、Issueを立てて開発に入る旨宣言いただくと嬉しいです。（私もこれからそうします）

**Comment by ghost** [comment]
@halsk さん
ご返信ありがとうございます。

優先度ならびに開発ルールについては承知いたしました。
API仕様書を確認後、まずstatus系のうち1つAPI実装のIssueを作成して着手させていただきます。


> 不明点も多いと思うので、随時聞いて頂けると助かります！

ありがとうございます。
適宜ご質問・認識合わせなどをさせていただればと思います。

**Comment by halsk** [comment]
追加の修正はあるものの、一旦は修了しているので、この Issue はクローズします。
