### ISSUE TITLE
npm run deploy 実行時のテンプレート参照エラー

### ISSUE THREAD

**Issue by shimpeiws** [codeforjapan/remote-patient-monitoring-api#35]
https://github.com/codeforjapan/remote-patient-monitoring-api/blob/8086899a00a8c8b343581331f909b465ac542083/docs/DEVELOPMENT.md#4-setup の手順にそって `npm run deploy && npm run deploy:gateway`  を実行時に以下warning表示後にデプロイが失敗しました

```
Serverless Warning --------------------------------------

  A valid file to satisfy the declaration 'file(./templates/functions-aws.yml)' could not be found.
```

templates配下には `functions-.yml` と `functions-true.yml` は存在するが、 `functions-aws.yml` は存在しないためこのエラーになっていると思います。

デプロイプロセス全体の関連を把握できていないのですが、セットアップ時に `/templates/functions-aws.yml` の追加が必要でしょうか?  あるいはデプロイ手順、serverless.ymlに何らか変更を加えるべきでしょうか?

**Comment by halsk** [comment]
@shimpeiws 
すみません。最新のものが上がっていませんでした。こちらで再度試してみていただけますでしょうか。
deploy プロセスや 技術 stack についてのドキュメンテーションもしなくてはですね・・・

**Comment by halsk** [comment]
すみません。間違えて　Issue 閉じてしまいましたが戻しました。修正確認できたらクローズ願います。

**Comment by shimpeiws** [comment]
@halsk 
早速FIXありがとうございます! 最新のdevelopをpullしてデプロイが完走することを確認しました :tada:

> deploy プロセスや 技術 stack についてのドキュメンテーションもしなくてはですね・・・

セットアップしつつserverless.yml関連を読んでいたところなので、自分の整理もかねてまとめてみようと思います。

serverlessの開発だと開発者全員がデプロイして試すのもなかなか難しいと思うので、E2Eテストから書く方針すごく良いと思います :+1:
unit testも適宜足していけば、ローカル実行/AWS デプロイなしてもだいぶ開発しやすくなるかな、と思ってます。
