### ISSUE TITLE
アプリのUIデザインを行う

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-api#4]
#3 と連動

**Comment by halsk** [comment]
こちらに、クライアントのワイヤーフレームを書きました。
https://www.figma.com/file/29X7k8bKfFlWS6Md5BhrME/UI-Template-Copy?node-id=41%3A0

**Comment by tkgshn** [comment]
UIデザイナーの高木です。デザインの基本方針についての確認です。


UX/UI デザイナーのMako-sanと連絡は取っていて基本的には

> **Mako-san**
ワイヤーフレームの時点でデザインも整っていること、先方からのデザイン要望が低いこともあり、現状のワイヤーをブラッシュアップする方向になりました。
急ぎ私の方でフォント、余白、カラー、コンポーネント調整を行い、それを全体の画面に適用する流れにしようと思っています。

> **高木**
エラーステートや確認画面はしっかり設定するべきと考えているので、可能であればこの辺りのUIをお願いできると有り難いです

で進めていこうと思っています。SwiftUIでiOSアプリの経験もあるので、基本的にはエラー表示・例外も[AppleのHIG](https://developer.apple.com/design/human-interface-guidelines/)準拠で進めていこうと思います ✌️

**Comment by kaizumaki** [comment]
figmaで進行中なので、こちらのissueはクローズします。
