### ISSUE TITLE
/patients/{patientId}/statuses POST 実装

### ISSUE THREAD

**Issue by ghost** [codeforjapan/remote-patient-monitoring-api#58]
### 対象API
- /api/admin/patients/{patientId}/statuses POST
- /api/nurse/patients/{patientId}/statuses POST
- /api/patient/patients/{patientId}/statuses POST

### Lambda名
- ~remote-Status-monitoring-postStatus-{Stage名}~
- remote-patient-monitoring-postStatus-${Stage名}
  - 他のLambdaの命名規則に合わせました。 

### 作業項目
- [x] 作業前の質問・確認事項洗い出し
- [x] API実装
- [x] 動作確認 (E2E)

### PR
-

**Comment by ghost** [comment]
### 1.  [クラス図(テーブル構成)](https://github.com/codeforjapan/remote-patient-monitoring-api/blob/develop/docs/uml/CLASSES.md)について
- 確認的な質問です。Status, SymptonはPatientと別にそれぞれテーブルを持つ形になりますでしょうか?
  - それともPatientテーブルのStatus属性に対してデータ(オブジェクト)追加になる想定でしょうか
  - もし別テーブルとする場合はStatusにpatientIdを持たせる形かPatientにStatusIdのリストを持たせる形になると思っております。

### 2. リクエストボディの仕様について
- 見落としていたら申し訳ありません。リクエストボディのパラメータのうち必須/任意パラメータはどこを参照すればよろしいでしょうか?

**Comment by ghost** [comment]
@halsk さん
五月雨で大変恐れ入ります。実装前に仕様について2点ご質問をさせていただきました。
お手すきの際にご回答をお願いいたします。

**Comment by halsk** [comment]
> 確認的な質問です。Status, SymptonはPatientと別にそれぞれテーブルを持つ形になりますでしょうか?
> それともPatientテーブルのStatus属性に対してデータ(オブジェクト)追加になる想定でしょうか
> もし別テーブルとする場合はStatusにpatientIdを持たせる形かPatientにStatusIdのリストを持たせる形になると思っております。

DynamoDB の場合、テーブル数を少なくする方が良いらしいですね。serverless の設定では別のテーブルを作ってしまいましたが、Patient に全部突っ込んでも良いかもしれません。（NoSQLはそんなに経験値無いので、ご意見あればぜひ）

**Comment by ghost** [comment]
@halsk さん
コメントありがとうございます。
そうですね。DynamoDBはできる限り集約した方がいいですね。

ただすみませんが、
たった今気づいたのですが今回 `statusId` を指定して病状報告を削除するAPIがあるのでデータ量によっては
Statusは別テーブルの方がいいかもしれません。

もしPatientにオブジェクトを入れる形にすると `/api/admin/statuses/{statusId}` と `/api/nurse/statuses/{statusId}`
の場合、以下のような処理になるのでパフォーマンスに懸念がありそうです。

```
1. Patientテーブルに対してスキャン
2. PatientのStatusesを検索(for文のロジック的なもの)
3. 該当のStatusIdのオブジェクトを削除
```

全体の仕様把握がまだできてないのでもしかしたら見当違いかもしれませんが、
StatusとSymptonは一つのテーブルに統合してもおそらく良さそうには今の所思いました。

**Comment by halsk** [comment]
なるほど。一応API的としては `/api/admin/statuses/{statusId}` と `/api/nurse/statuses/{statusId}` は書いてみましたが、クライアント側では 一番細かい画面はこれなんですよね。

![image](https://user-images.githubusercontent.com/16509/106454006-7d686900-64cd-11eb-8cca-c5b1f0fd543f.png)

ですので、このAPI自体実装しなくても良いかもしれません。後々削除や更新のユースケースが出てきたとしても、APIとしては
`/api/nurse/patients/{patientId}/statuses/{statusId}`

として、直接 statusId のみを指定して削除することはしないのが良さそうですがどうでしょうか。
patient 用APIも、直接 `/api/patient/statuses/{statusId}` を指定するのはやめて、上記に合わせることになります。

Status と Symptom は一緒で良いと思います。

**Comment by ghost** [comment]
@halsk さん
ありがとうございます。

> 直接 statusId のみを指定して削除することはしないのが良さそうですがどうでしょうか。

patientIdをクライアントから指定いただけると関連するテーブルに情報を集約しやすいので
とても良いと思います。

**Comment by ghost** [comment]
API定義書の方もアップデートいただきありがとうございます。
ご相談させていただいた方向で実装を進めようと思います。

**Comment by halsk** [comment]
API定義書、修正しました！
また、openapi の schema に必須フィールドも入れたので、SwaggerUI からSchema リンクで参照できます。

![image](https://user-images.githubusercontent.com/16509/106464252-c0313d80-64db-11eb-8aca-792f369aa0db.png)

**Comment by halsk** [comment]
#66 で解消
