### ISSUE TITLE
システムアーキテクチャを決める

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-api#6]
できるだけ運用しやすいことを重視。
AWSが望ましい

最新のユースケースシナリオはこちら
https://miro.com/app/board/o9J_laUr9s8=/
閲覧パスワードは remote-monitoring

ワイヤーフレームはこちら
https://www.figma.com/file/29X7k8bKfFlWS6Md5BhrME/UI-Template-Copy?node-id=41%3A0

**Comment by diizuka2** [comment]
- アクセス頻度が低いのであれば、AWSのLamba + RDS(DynamoDB? Timestream?)、GCPのCloudFunctions(GAE)+Cloud SQL が良いかもしれません。
- パルスオキシメーターのように、機械が定期的にデータ送付するならば、
    - スマホ経由でAWS SQS or GCP Pub/Subでデータを受け取ると良さそう
    - RDSじゃなくてAWS Timestreamで受けた方が良い？

**Comment by halsk** [comment]
Lambda + RDS でAPIサーバを立てるのが良さそうですね。ちなみに、パルスオキシメーター(RingO2)からのデータ送信は、定期的なPOSTクエリの送信みたいです。

**Comment by halsk** [comment]
構築のためのフレームワークは、Serverless Framework が良いかと思っていますが、どなたかアイデアありましたらお願いします。(手も動かせる方歓迎)

**Comment by NEKOYASAN** [comment]
Lambda -> RDSだとすると間にRDS Proxy挟んであげたほうが良いかもですね...
Lambda使うのであればDynamoとかの方が相性が良いかもという感じもありますがなんとも...
今回のような時系列データの場合TimeStreamの方がデータ処理はしやすそうです
(Serverless Framework 良いと思います！）

**Comment by halsk** [comment]
なるほど。Timestream 使ったことないですが、レコード削除できないのと、保持期間が限られているらしいので、DynamoDB が良さそうに思います。

**Comment by 1n-mas** [comment]
電話はある程度定型的な内容ならAmazon Connect（発信も可能）使ってはどうでしょうか？
（119は無理でしょうけれど、保健所はいけるはず。）

あとここで聞くことではないかもしれませんが、患者が削除しない限りデータずっと保持し続けるものでしょうか？
監視外れたものはスケジュール削除（１か月後？）したほうが良い気がします。

**Comment by halsk** [comment]
@1n-mas さんありがとうございます。
電話については、患者さんが具合が悪くなったときに保健所や119番へかけるものなので、そのまま `<a href="tel:">` での発信で大丈夫だと思います。

**Comment by y2naranja** [comment]
データを医療統計に利用する可能性があるのでそこは奥村先生に要確認だと思います。
基本的には、アーカイヴしてメインからは物理削除でよいのでは。

**Comment by halsk** [comment]
とりあえず、
Serverless framework を使い、APIGateway → Lambda → DynamoDB という構成でAPIを開発中です。
API 定義は、 Swagger.yaml で行っています。

**Comment by takahashim** [comment]
DynamoDBの場合、検索や集計が苦手（大変）なので、保健所側のUIであれも出したい・こういうことはできないかといった要件が後から出てくると大変そうな懸念があります。
とはいえ、いざとなればフルスキャンしてフロント側で何とかする（データ件数もめちゃめちゃ多いわけではないので）、と決めればいけるとは思います。

**Comment by halsk** [comment]
まだDynamoDBの部分までは作ってないのですが、将来的な構成を考えたら、最初からRDBにしておいた方が良いでしょうか？

https://dev.classmethod.jp/articles/using-relational-databases-with-aws-lambda-easy-connection-pooling/

最初の構成時の手間がそれほど増えないなら、それもありだとは思いました。

**Comment by NEKOYASAN** [comment]
> DynamoDBの場合、検索や集計が苦手（大変）なので、保健所側のUIであれも出したい・こういうことはできないかといった要件が後から出てくると大変そうな懸念があります。

これは確かにそうだと思います。

> 最初の構成時の手間がそれほど増えないなら、それもありだとは思いました。

さほど変わらないかなと思います。マネジメントコンソールで設定した後エンドポイントをProxy側にするだけで動作するはずです…！

**Comment by takahashim** [comment]
DynamoDBはデータ件数・アクセス頻度の両方でスケールしやすいのがメリットなのですが、今回のシステムはどちらも重要ではないのでちょっとメリットが弱いのかなと思いました。

でも、直近のデータのモニタリングが基本で、それ以外はあんまり必要ないはずということであれば、DynamoDBでも扱えると思います。時系列データと個人別のデータを別にもたせるとかもできますし、検索等をtrigger経由でバックエンド側で行って結果をためておく、とかも可能です。

そしてデータについて、

> データを医療統計に利用する可能性があるのでそこは奥村先生に要確認だと思います。
> 基本的には、アーカイヴしてメインからは物理削除でよいのでは。

ということであれば、

* モニタリング用はDynamoDBに集約
* アーカイブとして別のシステム・DBに移して、そこで分析に使う（モニタリングシステムでは参照しない）

といった使い方になるかと思います。

**Comment by MasaGon** [comment]
まだ仕様ザックリとしか見てないので、外してたら遠慮無くご指摘ください。

将来的な患者数増加や測定頻度向上を考えるなら、パルスオキシメータからの送信処理はIoTコア(HTTP/Websocket/MQTT)で捕まえておいて、そのトリガーでDynamoDBに突っ込めばlambda起動をスキップしてレイテイシを低減出来ると思います。（出来ればWebsocketかMQTTが良いけど、JavaScriptだとWebSocketになるのかな？）

集計とかいろいろやるコンパネ系は、皆さんがおっしゃっているようにRDBの方が取り回しが良いので、DynamoDBのストリームを捕まえるか、定期実行かでlambdaでサマライズ処理を走らせてRDBに投入する（管理系データはRDBオンリー）。つまり、DynamoDBをキュー的に使うハイブリッド実装が良いかもしれません。

あとは、RDS Proxyの代わりにAurora ServerlessのData APIというのもあり得るかもしれません。Data APIは僕は使ったことがないですが、Aurora Servelessは、ほぼシャットダウンされている（テストサーバーなど）とか、常に1台は目一杯動いていて、2台以上にスケールする事が時々あるというレベル以上であれば多少お得感が出ますかね。常に1台をちょっとだけ使っているとかいう状況だと多少お高めですが、まぁこれも普通のServerlessの方でどの程度冗長かけるかによりますね。

時期的に繁忙期なのでどこまでお手伝いできるか分かりませんが、Serverless FrameworkとIoT CoreからDynamoの高速データ流し込みあたりは実績ありますので、出来るだけフォローしたいと思います。

**Comment by halsk** [comment]
とりあえず、クラス図を作ってみました。

https://github.com/codeforjapan/remote-patient-monitoring-api/blob/develop/docs/uml/CLASSES.md

APIは引き続き実装していきますが、認証部分も含めたサーバ/クライアント部分をどう作るべきか皆さんのアイデアが欲しいです。

* 保健所 has many 患者
* 患者 has many 病状
* 看護師 has many 保健所

という形で、

* 看護師は担当する保健所の患者の病状しか見れない
* 患者は自分の入力した病状しか見れない

という認可をしなくてはいけません。
この認可の仕組みまで Cognito を使うのはちょっと難しそうな感じがしています。

**Comment by halsk** [comment]
#13  も関連。

**Comment by halsk** [comment]
ユーザ作成＋ログイン機構には Cognito を使い、ログイン後取得した token も lambda に送信、その token と ログインIDをAPIに送り正しいtokenかどうかをlambdaで確認してから認可するのが良いのかな

**Comment by halsk** [comment]
いや、やっぱり一般ユーザ用の UserPool をもう一つ作って、その UserPool を API Gateway の Authorization に組み込めば良いのか。

**Comment by shimpeiws** [comment]
@halsk 
AWSやServerless Frameworkでの開発の経験があり、何かcontributeできるところがあるかも、とこのIssueに来ました。

API Gateway + Lambdaの構成であればCognito User Poolを分けてAuthorizerで解決するのが簡潔でセキュアだと思います。

認可についてはアプリケーションレベルで制御するのか、DBの行レベルでアクセス許可を行うかが悩ましいと思います。

例えば、看護師は担当する保健所の患者の病状しか見れないのユースケースの場合...

- アプリケーションレベルで実装する場合、Nurse.Centersを取得した上で対象レコードをクエリする
- DynamoDB利用の場合に行レベルアクセス許可を行う場合は以下のようなイメージになるのかと思います
  - https://docs.aws.amazon.com/ja_jp/IAM/latest/UserGuide/reference_policies_examples_dynamodb_rows.html

アプリケーションレベルの方が実装は容易だと思いますが、アプリケーションの性質上認可の漏れがクリティカルになるのであればDBレベルでの制御も検討に入るかと思います。
