### ISSUE TITLE
ESLint , Prettierを導入する

### ISSUE THREAD

**Issue by ghost** [codeforjapan/remote-patient-monitoring-api#63]
### 内容
- ESLint, Prettierを導入することでTypeScriptのコーディング規約に沿ってかけるので何処かのタイミング(リファクタリングなど)で入れても良いかもしれません。

### 必要な作業
- ESLint ,Prettierのインストール
- Lintの設定
- Lintエラーになる部分の対応
  - リファクタリングの規模と要相談

**Comment by halsk** [comment]
いいですね。どこかでやって頂けると助かります！

**Comment by kenichisak** [comment]
こんばんは。

ローカルでちょっと試してみようと思った際に ESLint と Prettier を入れたのでご参考までに共有します。

https://github.com/kenichisak/remote-patient-monitoring-api/tree/feature/add-linter

設定は、基本的に下記の記事の方のやり方に準じています。
（ただし、今までの作業に影響しなように commit 時の自動強制実行はコメントアウトしてあります）

https://qiita.com/notakaos/items/85fd2f5c549f247585b1

お役にたちそうな部分ありましたら取り込んでいただけると幸いです。
