### ISSUE TITLE
モニタリングダッシュボード開発

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-api#8]
スマホから入力されたデータを表示するダッシュボード

**Comment by kaizumaki** [comment]
ダッシュボード、お手伝いします。figmaとmiroと一連のissueは拝見しました。
Nuxt.jsをSPAモードで立てるのがよいかと思いますが、どうでしょうね？
モニタリングのデータはAPIでGETするのだと思っていますが、間違っていたらご指摘ください。
APIとのつなぎ込みは後回しにして、figmaに合わせてコーディングを始めようかと思いますが、いかがでしょう。

**Comment by NEKOYASAN** [comment]
同じくお手伝いさせていただければと思います...!
このリポジトリに入力側とダッシュボード側どっちも一緒に入れるとごっちゃになりそうなのでリポジトリ２つに分けても良いかなと思っているのですがどうでしょう！

**Comment by halsk** [comment]
ありがとうございます！そうですね。
API、Dashboard、Mobile の3つのリポジトリに分割しましょうか。

**Comment by halsk** [comment]
このリポジトリ名を `remote-patient-monitoring-api` に変更し、
[remote-patient-monitoring-dashboard](https://github.com/codeforjapan/remote-patient-monitoring-dashboard)と、[remote-patient-monitoring-client](https://github.com/codeforjapan/remote-patient-monitoring-client) の2つのリポジトリを新たに作成しました。

**Comment by halsk** [comment]
https://github.com/codeforjapan/remote-patient-monitoring-dashboard
で開発を続行するので、こちらのIssueはクローズします。
