### ISSUE TITLE
GET /patients/{ID}/statuses の並び順が古い順である

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-api#80]
新しい順に並べたい

**Comment by kenichisak** [comment]
@halsk こんばんは。

こちらですが 本番運用まだ始まっていないと思ってますので

https://github.com/kenichisak/remote-patient-monitoring-api/commit/a8db36fb51477beecd4fa322a61731d9f19b95ef

のように変更してはどうかと思いました。

全体をちゃんと見ることが出来ていないため、見ていない部分への影響・勘違いや考慮漏れがあるかもしれないのでプルリクにはしてません。

問題なさそうであればプルリクお送りします。

よろしくお願いいたします。

**Comment by halsk** [comment]
@kenichisak 

おお、ありがとうございます！良さそうではありますね。
もし可能であれば、
`test/e2e/fulltest.spec.ts` にもテストを書いて検証頂けると大変ありがたいです。
fulltest には AWS の環境が必要なので、そこまでは難しい場合、ローカルのテストでも大丈夫です。

ローカルテストの方法

* `npm run dynamodb:start`
*  `npm run test:local`

テストを追加するファイル　`test/lambda/status.spec.ts`

(`npm run dynamodb:start` は、テストのたびに再起動する必要があります)

**Comment by kenichisak** [comment]
@halsk 

遅くなりましたが、プルリク送りましたのでご確認お願いいたします。

https://github.com/codeforjapan/remote-patient-monitoring-api/pull/82

テストはローカルでのみ実施しました。

**Comment by halsk** [comment]
#82 で解消しました。ありがとうございました！
